### ISSUE TITLE
Data containing `\ufeff` character can't be written out in a final report

### ISSUE THREAD

**Issue by MattTriano** [uchicago-dsi/uchicago-bead-challenge-validation-tool#14]
A user reported running into this error while running the `bead_inspector` tool from a CLI.

```python
Traceback (most recent call last):
  File "C:\Path\to\python_distro\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Path\to\python_distro\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\a_user\path\to\venv\Scripts\bead_inspector.exe\__main__.py", line 7, in <module>
  File "C:\Users\a_user\path\to\venv\lib\site-packages\bead_inspector\main.py", line 41, in main
    BEADChallengeDataValidator(
  File "C:\Users\a_user\path\to\venv\lib\site-packages\bead_inspector\validator.py", line 839, in __init__
    self.generate_report()
  File "C:\Users\a_user\path\to\venv\lib\site-packages\bead_inspector\validator.py", line 867, in generate_report
    self.reporter = ReportGenerator(
  File "C:\Users\a_user\path\to\venv\lib\site-packages\bead_inspector\reporting.py", line 37, in __init__
    self.write_report(overwrite_report)
  File "C:\Users\a_user\path\to\venv\lib\site-packages\bead_inspector\reporting.py", line 116, in write_report
    f.write(self.final_report)
  File "C:\Path\to\python_distro\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 2573: character maps to <undefined>
```

**Comment by MattTriano** [comment]
From preliminary research, the `\ufeff` character is a "Byte Order Mark" (BOM), which is typically used at the beginning of a text file to indicate the byte-order (endianness) of file's encoding (`\ufeff` indicates big-endian, `\ufffe` indicates little-endian).

I might be able to resolve this by just setting the encoding used to write out the report in `ReportGenerator.write_report()`.

I should create some test data with the different kinds of BOMs that might be present. Here's what that might look like in a test fixture.

```
def create_csv_file(file_path, csv_data: str, encoding: str = "utf-8", bom: Optional[str] = None):
    with open(file_path, "w+", newline="", encoding=encoding) as csvfile:
        if bom is not None:
            csvfile.write(bom)
        writer = csv.writer(csvfile)
        writer.writerows(csv_data)


@pytest.fixture
def challenges_file_with_ufeff_bom_char(temp_dir):
    csv_content = (
        "challenge,challenge_type,challenger,challenge_date,rebuttal_date,"
        "resolution_date,disposition,provider_id,technology,location_id,unit,"
        "reason_code,evidence_file_id,response_file_id,resolution,"
        "advertised_download_speed,download_speed,advertised_upload_speed,"
        "upload_speed,latency\n"
        "2,,,,,,,,,,,,,,,,,,,\n"
    )
    file_path = temp_dir.join("challenges.csv")
    csv_lines = [line.split(",") for line in csv_content.split("\n") if line]
    create_csv_file(file_path, csv_lines, encoding="utf-8", bom="\ufeff")
    return file_path
```

I'm not 100% sure that my understanding is correct (it seems a little odd that the character would be in position 2573 if this construct is supposed to be at the beginning of a file, but this is a first step in debugging).
